name: $(Rev:rrr)

trigger: none

pr: none

pool: 'DEFRA-COMMON-ubuntu2004-SSV3'

resources:
  repositories:
    - repository: PipelineCommon
      name: DEFRA-DEVOPS-COMMON/Defra.Pipeline.Common
      type: git
      ref: refs/tags/Release-v6-latest

schedules:
  - cron: "0 0 * * 1"
    displayName: Weekly midnight build.
    branches:
      include:
        - main

extends:
  template: /templates/pipelines/common-scripts-deploy.yaml@PipelineCommon
  parameters:
    # keyVaultName: $(keyVaultName)
    # keyVaultSecretsFilter: 'DEVSTWINFACR1001-ADMIN-PASSWORD'
    variableFiles:
      - /azure-pipelines/vars/common.yaml@self
      - /azure-pipelines/vars/{environment}.yaml@self
    regionalVariableFiles:
      - /azure-pipelines/vars/regional/{region}.yaml@self
    environments:
      - name: 'dev'
        azureRegions:
          primary: northeurope
        developmentEnvironment: true
        deploymentBranches:
          - '*'
        serviceConnection: AZR-STW-DEV1
    scriptsList:
      - displayName: AzureCleanup
        type: AzureCLI
        AzureCLIScriptType: pscore
        scriptPath: azure-pipelines/scripts/cleanup.ps1
        filePathsForTransform:
          - azure-pipelines/scripts/cleanup.ps1.json
        scriptArguments: >
          -RESOURCE_GROUP $(serviceBusRGP)
          -NAME_SPACE $(serviceBusNamespaceName)
          -DEVELOPER_LIST $(developerList)