parameters:
- name: deployTag
  displayName: "Enter Docker Tag for image to be deployed"
  type: string
  default: 'latest'
- name: buildMajor
  displayName: "Major build version, default 0"
  default: 0
- name: buildMinor
  displayName: "Minor build version, default 0"
  default: 0

name: ${{ parameters.buildMajor }}.${{ parameters.buildMinor }}.$(Rev:rrr)

trigger: none

pr: none

pool: 'DEFRA-COMMON-ubuntu2004-SSV3'

variables:
  - name: deployTag
    value: ${{ parameters.deployTag }}

resources:
  repositories:
    - repository: PipelineCommon
      name: DEFRA-DEVOPS-COMMON/Defra.Pipeline.Common
      type: git
      ref: refs/tags/Release-v5-latest

extends:
  template: /templates/pipelines/common-scripts-deploy.yaml@PipelineCommon
  parameters:
    keyVaultName: $(keyVaultName)
    keyVaultSecretsFilter: 'DEVSTWINFACR1001-ADMIN-PASSWORD'
    variableFiles:
      - /azure-pipelines/vars/{environment}.yaml@self
    regionalVariableFiles:
      - /azure-pipelines/vars/regional/{region}.yaml@self
    environments:
      - name: 'dev'
        azureRegions:
          primary: northeurope
        developmentEnvironment: true
        deploymentBranches:
          - '*'
        serviceConnection: AZR-STW-DEV1
    scriptsList:
      - displayName: DockerInstallImage
        type: AzureCLI
        AzureCLIScriptType: pscore
        scriptPath: azure-pipelines/scripts/docker-artifact-deploy.ps1
        filePathsForTransform:
          - azure-pipelines/scripts/docker-artifact-deploy.ps1.json
        scriptArguments: >
          -DEPLOY_TAG $(deployTag)
          -DOCKER_SECRET $(DEVSTWINFACR1001-ADMIN-PASSWORD)
          -ACR_REGISTRY_SERVER $(acrServerName)
          -ACR_REGISTRY_USERNAME $(acrUsername)
          -APP_NAME $(functionAppName)
          -RESOURCE_GROUP $(functionAppRG)
          -KEYVAULT_NAME $(keyVaultName)
          -CONTAINER_REGISTRY $(acrName)
